server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.217.130:3306/tensquare_base
    password: 123456
    username: root
  jpa:
    database: mysql
    show-sql: true